"""Цвета и строки интерфейса (русский)."""

C = {
    "up":      "#00ff9f",
    "dn":      "#00d4ff",
    "total":   "#ffd700",
    "online":  "#00ff9f",
    "offline": "#555577",
    "dim":     "#7760aa",
    "warn":    "#ff8c00",
    "err":     "#ff2d78",
    "accent":  "#ff2d78",
    "accent2": "#9b30ff",
    "accent3": "#00d4ff",
    "ok":      "#00ff9f",
    "spark_u": "green",
    "spark_d": "cyan",
}

L: dict = {
    "title":             "Мониторинг Xray",
    "tab_dashboard":     "Панель",
    "tab_keys":          "Ключи",
    "tab_system":        "Система",
    "tab_logs":          "Логи",
    "tab_connections":   "Подключения",
    "tab_mgmt":          "Управление",
    "overview":          "ОБЗОР",
    "breakdown":         "РАЗБИВКА ТРАФИКА",
    "users":             "ПОЛЬЗОВАТЕЛИ",
    "system":            "СИСТЕМА",
    "online":            "онлайн",
    "conn":              "подкл",
    "inbound":           "ВХОДЯЩИЕ",
    "outbound":          "ИСХОДЯЩИЕ",
    "no_traffic":        "Нет данных о трафике",
    "no_users":          "Нет данных",
    "enable_hint":       "Включите statsUserOnline в policy",
    "log_title":         "ЛОГ ДОСТУПА",
    "log_empty":         "Лог не найден",
    "uptime":            "аптайм",
    "goroutines":        "потоки",
    "alloc":             "аллок",
    "mem":               "память",
    "gc":                "GC",
    "objects":           "объект",
    "waiting":           "подключение…",
    "connected":         "ОНЛАЙН",
    "disconnected":      "ОФФЛАЙН",
    "reconnecting":      "Переподключение…",
    "stats_reset":       "Счётчики сброшены!",
    "reset_fail":        "Ошибка сброса",
    "paused":            "ПАУЗА",
    "session_up":        "сессия ↑",
    "session_dn":        "сессия ↓",
    "no_conn_log":       "Событий нет",
    "conn_log":          "ЖУРНАЛ ПОДКЛЮЧЕНИЙ",
    "sort_down":         "Сорт: ↓ Загрузка",
    "sort_up":           "Сорт: ↑ Отдача",
    "sort_total":        "Сорт: Σ Всего",
    "keys_title":        "УПРАВЛЕНИЕ КЛЮЧАМИ",
    "config_ok":         "Конфиг OK",
    "config_err":        "Ошибка конфига",
    "xray_restarted":    "Xray перезапущен",
    "xray_restart_fail": "Ошибка перезапуска",
    "xray_reloaded":     "Конфиг перезагружен",
    "xray_reload_fail":  "Ошибка перезагрузки",
    "sys_cpu":           "CPU",
    "sys_ram":           "RAM",
    "sys_disk":          "Диск",
    "sys_load":          "Нагрузка",
    "sys_conn":          "TCP подкл",
    "sys_latency":       "Задержка",
    "sys_temp":          "Темп",
    "ping_fail":         "недоступен",
    "summary":           "Итого",
    "filter_placeholder":     "Фильтр пользователей...",
    "server_ip_placeholder":  "IP или домен сервера (авто если пусто)",
    "vless_url":         "VLESS URL",
    "rolled_back_to":    "Откат выполнен: {bak}",
    "path":              "Путь",
    "pid":               "PID",
    "status":            "СТАТУС",
    "boot":              "ЗАГРУЗКА",
    "github":            "GitHub",
    "latest_version_check": "ПРОВЕРКА ПОСЛЕДНЕЙ ВЕРСИИ",
    "tcp_connections":   "TCP подключения",
    "top_procs_ram":     "Топ процессов (RAM)",
    "dns_check":         "DNS проверка",
    "no_matches":        "Совпадений нет",
    "no_matches_for":    "Совпадений нет для",
    "url_saved":         "URL сохранён в /tmp/xray-clipboard.txt",
    "psutil_hint":       "pip install psutil",
    "xray_url_sent":     "URL отправлен в xray-clipboard.txt",
    "error_path_nano":   "Ошибка: {err}. Путь: nano {path}",
    "status_label":      "СТАТУС",
    "pid_label":         "PID",
    "ver_label":         "VER",
    "boot_label":        "ЗАГРУЗКА",
    "mem_label":         "MEM",
    "enabled_label":     "включено",
    "disabled_label":    "выключено",
    "cpu_label":         "CPU",
    "ram_label":         "RAM",
    "used_label":        "использовано",
    "free_label":        "свободно",
    "established_label": "УСТАНОВЛЕНО",
    "listen_label":      "СЛУШАТЬ",
    "processes_label":   "Процессы",
    "xray_pid_label":    "Xray PID",
    "xray_ram_label":    "Xray RAM",
    "xray_cpu_label":    "Xray CPU",
    "rx_label":          "-> rx",
    "tx_label":          "<- tx",
    "total_rx_label":    "Total rx",
    "total_tx_label":    "Total tx",
    "top_blocked":       "ТОП БЛОКИРОВОК",
    "target_label":      "TARGET",
    "block_label":       "BLOCK",
    "today_label":       "Today",
    "xray_started":      "Xray запущен",
    "xray_start_fail":   "Ошибка запуска",
    "xray_stopped":      "Xray остановлен",
    "xray_stop_fail":    "Ошибка остановки",
    "xray_enabled":      "Автозапуск Xray включён",
    "xray_disabled":     "Автозапуск Xray выключен",
    "xray_update_checking":    "Проверка обновлений...",
    "xray_update_downloading": "Скачивание обновления...",
    "xray_update_installing":  "Установка обновления...",
    "xray_update_done":        "Обновление завершено",
    "xray_update_fail":        "Ошибка обновления",
    "xray_update_latest":      "Установлена последняя версия",
    "xray_version":      "Версия Xray",
    "xray_latest":       "последняя",
    "xray_status":       "Статус Xray",
    "xray_running":      "работает",
    "xray_not_running":  "остановлен",
    "xray_mgmt":         "УПРАВЛЕНИЕ XRAY",
    "xray_not_found":    "xray не найден",
    "github_label":      "GitHub",
    "update_available":  "[ОБНОВЛЕНИЕ ДОСТУПНО]",
    "hotkeys_title":     "ГОРЯЧИЕ КЛАВИШИ",
    "access_keys_title": "КЛЮЧИ ДОСТУПА",
    "hotkey_start_xray":       "Запустить Xray",
    "hotkey_stop_xray":        "Остановить Xray",
    "hotkey_restart_xray":     "Перезапустить Xray",
    "hotkey_update_xray":      "Обновить Xray-core",
    "hotkey_toggle_autostart": "Переключить автозапуск",
    "hotkey_check_config":     "Проверить синтаксис конфига",
    "hotkey_edit_config":      "Редактировать конфиг (nano)",
    "hotkey_rollback_config":  "Откат конфига",
    "auto_backup":       "авто-бэкап",
    "restore_backup":    "восстановить последний бэкап",
    "bind_quit":         "Выход",
    "bind_reconnect":    "Реконнект",
    "bind_sort":         "Сортировка",
    "bind_reset":        "Сброс",
    "bind_pause":        "Пауза",
    "bind_qr":           "QR",
    "bind_restart":      "Рестарт",
    "bind_edit":         "Редактировать",
    "bind_check":        "Проверка",
    "bind_rollback":     "Откат",
    "bind_start":        "Старт",
    "bind_stop":         "Стоп",
    "bind_update":       "Обновить",
    "bind_toggle":       "Вкл/Выкл",
    "resumed":           "Продолжение",
    "enter_server_ip_first": "Введите IP сервера",
    "no_clients":        "Клиентов не найдено в config.json",
    "no_email":          "(нет email)",
    "enter_server_ip_url": "Введите IP сервера ниже для URL",
    "qr_first_client":   "[Q] QR первого клиента",
    "url_saved_qr":      "URL сохранён в /tmp/xray-clipboard.txt (pip install qrcode для QR)",
    "config_not_found":  "Конфигурация не найдена: {path}",
    "backup_done":       "Бэкап: {bak}",
    "config_reloaded_hint": "Конфиг перезагружен. R для перезапуска xray",
    "no_backups_found":  "Бэкапов не найдено",
    "rollback_error":    "Ошибка отката: {err}",
    "error_msg":         "ОШИБКА: {msg}",
    "error_label":       "Ошибка: {err}",
    "path_label":        "Путь:",
    "error_lower":       "ошибка: {err}",
    "edit_config_hint":  "[e] Открыть конфиг в nano (авто-бэкап)",
    "check_rollback":    "[C] Проверка  [B] Откат к бэкапу",
    "inbound_config":    "ВХОДЯЩАЯ КОНФИГУРАЦИЯ",
    "log_blocked":       "заблокировано:",
    "target_header":     "ЦЕЛЬ",
    "block_header":      "БЛОК",
    "percent_symbol":    "%",
    "session":           "сессия",
}
