"""Colors and i18n strings."""

C = {
    "up":      "#00ff9f",
    "dn":      "#00d4ff",
    "total":   "#ffd700",
    "online":  "#00ff9f",
    "offline": "#555577",
    "dim":     "#7760aa",
    "warn":    "#ff8c00",
    "err":     "#ff2d78",
    "accent":  "#ff2d78",
    "accent2": "#9b30ff",
    "accent3": "#00d4ff",
    "ok":      "#00ff9f",
    "spark_u": "green",
    "spark_d": "cyan",
}

LANG = {
    "en": {
        "title":"Xray Monitor",
        "tab_dashboard": "Dashboard", "tab_keys": "Keys", "tab_system": "System", "tab_logs": "Logs", "tab_connections": "Connections", "tab_mgmt": "Management",
        "overview":"OVERVIEW", "breakdown":"TRAFFIC BREAKDOWN", "users":"USERS",
        "system":"SYSTEM", "online":"online", "conn":"conn",
        "inbound":"INBOUND", "outbound":"OUTBOUND",
        "no_traffic":"No traffic data yet", "no_users":"No user data",
        "enable_hint":"Enable statsUserOnline in policy",
        "log_title":"ACCESS LOG", "log_empty":"Log not found",
        "uptime":"uptime", "goroutines":"goroutines", "alloc":"alloc",
        "mem":"sys mem", "gc":"GC runs", "objects":"live obj",
        "waiting":"connecting…", "connected":"LIVE", "disconnected":"OFFLINE",
        "reconnecting":"Reconnecting…", "stats_reset":"Counters zeroed!",
        "reset_fail":"Reset failed", "paused":"PAUSED",
        "session_up":"session ↑", "session_dn":"session ↓",
        "no_conn_log":"No connection events yet", "conn_log":"CONNECTION LOG",
        "sort_down":"Sort: ↓ Download", "sort_up":"Sort: ↑ Upload",
        "sort_total":"Sort: Σ Total",
        "keys_title":"KEY MANAGEMENT",
        "config_ok":"Config OK", "config_err":"Config error",
        "xray_restarted":"Xray restarted", "xray_restart_fail":"Restart failed",
        "xray_reloaded":"Config reloaded", "xray_reload_fail":"Reload failed",
        "sys_cpu":"CPU", "sys_ram":"RAM", "sys_disk":"Disk",
        "sys_load":"Load", "sys_conn":"TCP conns",
        "sys_latency":"Latency", "sys_temp":"Temp",
        "ping_fail":"unreachable",
        "lang_switched":"Language: English",
        "summary":"Summary",
        "access_key":"Access key", "last_used":"Last used",
        # Xray management
        "xray_started":"Xray started", "xray_start_fail":"Start failed",
        "xray_stopped":"Xray stopped", "xray_stop_fail":"Stop failed",
        "xray_enabled":"Xray autostart enabled", "xray_disabled":"Xray autostart disabled",
        "xray_update_checking":"Checking for updates...",
        "xray_update_downloading":"Downloading update...",
        "xray_update_installing":"Installing update...",
        "xray_update_done":"Update complete",
        "xray_update_fail":"Update failed",
        "xray_update_latest":"Already on latest version",
        "xray_version":"Xray version", "xray_latest":"latest",
        "xray_status":"Xray status",
        "xray_running":"running", "xray_not_running":"stopped",
        "xray_mgmt":"XRAY MANAGEMENT",
        # Bindings
        "bind_quit":"Quit", "bind_reconnect":"Reconnect", "bind_sort":"Sort",
        "bind_reset":"Reset", "bind_pause":"Pause", "bind_lang":"Language",
        "bind_qr":"QR", "bind_restart":"Restart", "bind_edit":"Edit",
        "bind_check":"Check", "bind_rollback":"Rollback", "bind_start":"Start",
        "bind_stop":"Stop", "bind_update":"Update", "bind_toggle":"Toggle",
        # Keys panel
        "resumed":"Resumed", "enter_server_ip_first":"Enter server IP first",
        "no_clients":"No clients found in config.json", "no_email":"(no email)",
        "enter_server_ip_url":"Enter server IP below for URL",
        "qr_first_client":"[Q] QR first client",
        "edit_config_hint":"[e] Open config in nano (auto-backup)",
        "check_rollback":"[C] Check syntax  [B] Rollback to backup",
        "inbound_config":"INBOUND CONFIG",
    },
    "ru": {
        "title":"Мониторинг Xray",
        "tab_dashboard": "Панель", "tab_keys": "Ключи", "tab_system": "Система", "tab_logs": "Логи", "tab_connections": "Подключения", "tab_mgmt": "Управление",
        "overview":"ОБЗОР", "breakdown":"РАЗБИВКА ТРАФИКА", "users":"ПОЛЬЗОВАТЕЛИ",
        "system":"СИСТЕМА", "online":"онлайн", "conn":"подкл",
        "inbound":"ВХОДЯЩИЕ", "outbound":"ИСХОДЯЩИЕ",
        "no_traffic":"Нет данных о трафике", "no_users":"Нет данных",
        "enable_hint":"Включите statsUserOnline в policy",
        "log_title":"ЛОГ ДОСТУПА", "log_empty":"Лог не найден",
        "uptime":"аптайм", "goroutines":"потоки", "alloc":"аллок",
        "mem":"память", "gc":"GC", "objects":"объект",
        "waiting":"подключение…", "connected":"ОНЛАЙН", "disconnected":"ОФФЛАЙН",
        "reconnecting":"Переподключение…", "stats_reset":"Счётчики сброшены!",
        "reset_fail":"Ошибка сброса", "paused":"ПАУЗА",
        "session_up":"сессия ↑", "session_dn":"сессия ↓",
        "no_conn_log":"Событий нет", "conn_log":"ЖУРНАЛ ПОДКЛЮЧЕНИЙ",
        "sort_down":"Сорт: ↓ Загрузка", "sort_up":"Сорт: ↑ Отдача",
        "sort_total":"Сорт: Σ Всего",
        "keys_title":"УПРАВЛЕНИЕ КЛЮЧАМИ",
        "config_ok":"Конфиг OK", "config_err":"Ошибка конфига",
        "xray_restarted":"Xray перезапущен", "xray_restart_fail":"Ошибка перезапуска",
        "xray_reloaded":"Конфиг перезагружен", "xray_reload_fail":"Ошибка перезагрузки",
        "sys_cpu":"CPU", "sys_ram":"RAM", "sys_disk":"Диск",
        "sys_load":"Нагрузка", "sys_conn":"TCP подкл",
        "sys_latency":"Задержка", "sys_temp":"Темп",
        "ping_fail":"недоступен",
        "lang_switched":"Язык: Русский",
        "summary":"Итого",
        # Xray management
        "xray_started":"Xray запущен", "xray_start_fail":"Ошибка запуска",
        "xray_stopped":"Xray остановлен", "xray_stop_fail":"Ошибка остановки",
        "xray_enabled":"Автозапуск Xray включён", "xray_disabled":"Автозапуск Xray выключен",
        "xray_update_checking":"Проверка обновлений...",
        "xray_update_downloading":"Скачивание обновления...",
        "xray_update_installing":"Установка обновления...",
        "xray_update_done":"Обновление завершено",
        "xray_update_fail":"Ошибка обновления",
        "xray_update_latest":"Установлена последняя версия",
        "xray_version":"Версия Xray", "xray_latest":"последняя",
        "xray_status":"Статус Xray",
        "xray_running":"работает", "xray_not_running":"остановлен",
        "xray_mgmt":"УПРАВЛЕНИЕ XRAY",
        # Bindings
        "bind_quit":"Выход", "bind_reconnect":"Реконнект", "bind_sort":"Сортировка",
        "bind_reset":"Сброс", "bind_pause":"Пауза", "bind_lang":"Язык",
        "bind_qr":"QR", "bind_restart":"Рестарт", "bind_edit":"Редактировать",
        "bind_check":"Проверка", "bind_rollback":"Откат", "bind_start":"Старт",
        "bind_stop":"Стоп", "bind_update":"Обновить", "bind_toggle":"Вкл/Выкл",
        # Keys panel
        "resumed":"Продолжение", "enter_server_ip_first":"Введите IP сервера",
        "no_clients":"Клиентов не найдено в config.json", "no_email":"(нет email)",
        "enter_server_ip_url":"Введите IP сервера ниже для URL",
        "qr_first_client":"[Q] QR первого клиента",
        "edit_config_hint":"[e] Открыть конфиг в nano (авто-бэкап)",
        "check_rollback":"[C] Проверка  [B] Откат к бэкапу",
        "inbound_config":"ВХОДЯЩАЯ КОНФИГУРАЦИЯ",
    },
}
