"""Colors and i18n strings."""

C = {
    "up":      "#00ff9f",
    "dn":      "#00d4ff",
    "total":   "#ffd700",
    "online":  "#00ff9f",
    "offline": "#555577",
    "dim":     "#7760aa",
    "warn":    "#ff8c00",
    "err":     "#ff2d78",
    "accent":  "#ff2d78",
    "accent2": "#9b30ff",
    "accent3": "#00d4ff",
    "ok":      "#00ff9f",
    "spark_u": "green",
    "spark_d": "cyan",
}

LANG = {
    "en": {
        "title":"Xray Monitor",
        "overview":"OVERVIEW", "breakdown":"TRAFFIC BREAKDOWN", "users":"USERS",
        "system":"SYSTEM", "online":"online", "conn":"conn",
        "inbound":"INBOUND", "outbound":"OUTBOUND",
        "no_traffic":"No traffic data yet", "no_users":"No user data",
        "enable_hint":"Enable statsUserOnline in policy",
        "log_title":"ACCESS LOG", "log_empty":"Log not found",
        "uptime":"uptime", "goroutines":"goroutines", "alloc":"alloc",
        "mem":"sys mem", "gc":"GC runs", "objects":"live obj",
        "waiting":"connecting…", "connected":"LIVE", "disconnected":"OFFLINE",
        "reconnecting":"Reconnecting…", "stats_reset":"Counters zeroed!",
        "reset_fail":"Reset failed", "paused":"PAUSED",
        "session_up":"session ↑", "session_dn":"session ↓",
        "no_conn_log":"No connection events yet", "conn_log":"CONNECTION LOG",
        "sort_down":"Sort: ↓ Download", "sort_up":"Sort: ↑ Upload",
        "sort_total":"Sort: Σ Total",
        "keys_title":"KEY MANAGEMENT",
        "config_ok":"Config OK", "config_err":"Config error",
        "xray_restarted":"Xray restarted", "xray_restart_fail":"Restart failed",
        "xray_reloaded":"Config reloaded", "xray_reload_fail":"Reload failed",
        "sys_cpu":"CPU", "sys_ram":"RAM", "sys_disk":"Disk",
        "sys_load":"Load", "sys_conn":"TCP conns",
        "sys_latency":"Latency", "sys_temp":"Temp",
        "ping_fail":"unreachable",
        "lang_switched":"Language: English",
    },
    "ru": {
        "title":"Мониторинг Xray",
        "overview":"ОБЗОР", "breakdown":"РАЗБИВКА ТРАФИКА", "users":"ПОЛЬЗОВАТЕЛИ",
        "system":"СИСТЕМА", "online":"онлайн", "conn":"подкл",
        "inbound":"ВХОДЯЩИЕ", "outbound":"ИСХОДЯЩИЕ",
        "no_traffic":"Нет данных о трафике", "no_users":"Нет данных",
        "enable_hint":"Включите statsUserOnline в policy",
        "log_title":"ЛОГ ДОСТУПА", "log_empty":"Лог не найден",
        "uptime":"аптайм", "goroutines":"потоки", "alloc":"аллок",
        "mem":"память", "gc":"GC", "objects":"объект",
        "waiting":"подключение…", "connected":"ОНЛАЙН", "disconnected":"ОФФЛАЙН",
        "reconnecting":"Переподключение…", "stats_reset":"Счётчики сброшены!",
        "reset_fail":"Ошибка сброса", "paused":"ПАУЗА",
        "session_up":"сессия ↑", "session_dn":"сессия ↓",
        "no_conn_log":"Событий нет", "conn_log":"ЖУРНАЛ ПОДКЛЮЧЕНИЙ",
        "sort_down":"Сорт: ↓ Загрузка", "sort_up":"Сорт: ↑ Отдача",
        "sort_total":"Сорт: Σ Всего",
        "keys_title":"УПРАВЛЕНИЕ КЛЮЧАМИ",
        "config_ok":"Конфиг OK", "config_err":"Ошибка конфига",
        "xray_restarted":"Xray перезапущен", "xray_restart_fail":"Ошибка перезапуска",
        "xray_reloaded":"Конфиг перезагружен", "xray_reload_fail":"Ошибка перезагрузки",
        "sys_cpu":"CPU", "sys_ram":"RAM", "sys_disk":"Диск",
        "sys_load":"Нагрузка", "sys_conn":"TCP подкл",
        "sys_latency":"Задержка", "sys_temp":"Темп",
        "ping_fail":"недоступен",
        "lang_switched":"Язык: Русский",
    },
}
